import tkinter as tk
from tkinter import ttk


def build_add_page(app):
    mix = app.mix_color
    RoundedTag = app.RoundedTag
    app.add_page = tk.Frame(app.root, bg=app.bg_color, padx=34, pady=28)
    header_row = tk.Frame(app.add_page, bg=app.bg_color)
    header_row.pack(fill="x")
    app.back_button = ttk.Button(header_row, text="← 返回", command=app._back_to_main)
    app.back_button.pack(side="left")
    app.add_page_title = RoundedTag(header_row, text="添加个人词库", text_font=(app.cn_font_family, 18, "bold"), bg=app.bg_color, fg=app.config.theme_color, fill=mix(app.config.theme_color, "#ffffff", 0.86), outline=app.config.theme_color, radius=16, padx=20, pady=8)
    app.add_page_title.pack(side="left", padx=(18, 0))
    add_panel = tk.Frame(app.add_page, bg=app.card_color, highlightthickness=0, bd=0, padx=20, pady=16)
    add_panel.pack(fill="x", pady=(16, 12))
    add_tag = RoundedTag(add_panel, text="添加单词", text_font=(app.cn_font_family, 12, "bold"), bg=app.card_color, fg=app.config.theme_color, fill=mix(app.config.theme_color, "#ffffff", 0.88), outline=app.config.theme_color, radius=14, padx=16, pady=7)
    add_tag.pack(anchor="w")
    add_row = tk.Frame(add_panel, bg=app.card_color)
    add_row.pack(fill="x", pady=(10, 0))
    app.add_word_entry = ttk.Entry(add_row, textvariable=app.add_word_var, font=(app.en_font_family, 11))
    app.add_word_entry.pack(side="left", fill="x", expand=True, ipady=4)
    app.add_word_entry.bind("<Return>", app._add_single_word)
    app.add_word_button = ttk.Button(add_row, text="添加", command=app._add_single_word)
    app.add_word_button.pack(side="left", padx=(8, 0))
    import_panel = tk.Frame(app.add_page, bg=app.card_color, highlightthickness=0, bd=0, padx=20, pady=16)
    import_panel.pack(fill="x", pady=(0, 12))
    import_tag = RoundedTag(import_panel, text="导入单词(txt)", text_font=(app.cn_font_family, 12, "bold"), bg=app.card_color, fg=app.config.theme_color, fill=mix(app.config.theme_color, "#ffffff", 0.88), outline=app.config.theme_color, radius=14, padx=16, pady=7)
    import_tag.pack(anchor="w")
    import_row = tk.Frame(import_panel, bg=app.card_color)
    import_row.pack(fill="x", pady=(10, 0))
    app.import_entry = ttk.Entry(import_row, textvariable=app.import_file_var, font=(app.en_font_family, 10))
    app.import_entry.pack(side="left", fill="x", expand=True, ipady=4)
    app.import_browse_button = ttk.Button(import_row, text="选择文件", command=app._select_import_file)
    app.import_browse_button.pack(side="left", padx=(8, 8))
    app.import_button = ttk.Button(import_row, text="导入", command=app._import_words)
    app.import_button.pack(side="left")
    app.export_button = ttk.Button(import_row, text="导出正在背", command=app._export_learning_words)
    app.export_button.pack(side="left", padx=(8, 0))
    app.add_status_label = tk.Label(app.add_page, textvariable=app.add_status_var, bg=app.bg_color, fg=app.text_secondary, font=(app.cn_font_family, 10))
    app.add_status_label.pack(anchor="w", pady=(0, 10))
    lists_panel = tk.Frame(app.add_page, bg=app.bg_color)
    lists_panel.pack(fill="both", expand=True)
    learning_panel = tk.Frame(lists_panel, bg=app.card_color, padx=16, pady=14)
    learning_panel.pack(side="left", fill="both", expand=True, padx=(0, 8))
    finished_panel = tk.Frame(lists_panel, bg=app.card_color, padx=16, pady=14)
    finished_panel.pack(side="left", fill="both", expand=True, padx=(8, 0))
    app.learning_tag = RoundedTag(learning_panel, text="正在背（0）", text_font=(app.cn_font_family, 11, "bold"), bg=app.card_color, fg=app.config.theme_color, fill=mix(app.config.theme_color, "#ffffff", 0.9), outline=app.config.theme_color, radius=12, padx=14, pady=6)
    app.learning_tag.pack(anchor="w", pady=(0, 8))
    app.finished_tag = RoundedTag(finished_panel, text="背诵完成（0）", text_font=(app.cn_font_family, 11, "bold"), bg=app.card_color, fg=app.config.theme_color, fill=mix(app.config.theme_color, "#ffffff", 0.9), outline=app.config.theme_color, radius=12, padx=14, pady=6)
    app.finished_tag.pack(anchor="w", pady=(0, 8))
    app.learning_listbox = tk.Listbox(learning_panel, font=(app.en_font_family, 10), relief="flat", bd=0)
    app.learning_listbox.pack(fill="both", expand=True)
    app.finished_listbox = tk.Listbox(finished_panel, font=(app.en_font_family, 10), relief="flat", bd=0)
    app.finished_listbox.pack(fill="both", expand=True)
    app.learning_listbox.bind("<Button-3>", lambda event: app._open_word_menu(event, "learning"))
    app.finished_listbox.bind("<Button-3>", lambda event: app._open_word_menu(event, "finished"))
    app.learning_listbox.bind("<Double-Button-1>", lambda event: app._query_selected_word("learning"))
    app.finished_listbox.bind("<Double-Button-1>", lambda event: app._query_selected_word("finished"))
    app.word_menu = tk.Menu(app.root, tearoff=0)
    app.word_menu.add_command(label="查询", command=app._query_menu_word)
    app.word_menu.add_command(label="移出清单", command=app._remove_menu_word)
    app.word_menu_target = None
    app.word_menu_list_name = None
    app.add_page_tags = [app.add_page_title, add_tag, import_tag, app.learning_tag, app.finished_tag]
    app.add_page_panels = [add_panel, import_panel, learning_panel, finished_panel]
